name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  ruff-format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v4.0.0
