name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff-format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Check Python formatting
        run: uv tool run ruff format --check --line-length 100 .
