name: Format and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v4.0.0

      - run: ruff format --check
